# Generated by Django 6.0.1 on 2026-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_images/default.jpg', upload_to='menu_images/'),
        ),
    ]
