# Generated by Django 6.0.1 on 2026-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitem_image_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
